# Default values for sli-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: danielinclouds/sli-server
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 8080

istio:
  enabled: true
  host: "*"

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
